### ISSUE TITLE
转换llama2 70B模型时遇到的问题

### ISSUE THREAD

**Issue by zbtrs** [openppl-public/ppl.pmx#25]
如果直接用Model_zoo下的facebook来转换llama2 70B，需要MP=8，但是机器上并没有8张卡，设置--nproc_per_node 8会出错
如果用huggingface的转换脚本则会报错：Traceback (most recent call last):
  File "/data/asc24llama/zbtrs/ppl.pmx/model_zoo/llama/huggingface/ConvertWeightToPmx.py", line 132, in <module>
    main()
  File "/data/asc24llama/zbtrs/ppl.pmx/model_zoo/llama/huggingface/ConvertWeightToPmx.py", line 126, in main
    write_pmx_model(
  File "/data/asc24llama/zbtrs/ppl.pmx/model_zoo/llama/huggingface/ConvertWeightToPmx.py", line 92, in write_pmx_model
    wk = unpermute(hf_model_state_dict[f"model.layers.{layer_i}.self_attn.k_proj.weight"], num_kv_heads, key_value_dim, hidden_dim)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/asc24llama/zbtrs/ppl.pmx/model_zoo/llama/huggingface/ConvertWeightToPmx.py", line 83, in unpermute
    return w.view(n_heads, 2, dim1 // n_heads // 2, dim2).transpose(1, 2).reshape(dim1, dim2)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: shape '[8, 2, 512, 8192]' is invalid for input of size 8388608

**Comment by Alcanderian** [comment]
facebook的模型可以先使用

**Comment by Alcanderian** [comment]
facebook的模型可以先使用merge model工具进行
https://github.com/openppl-public/ppl.pmx/tree/master/model_zoo/llama/huggingface#merging-model

**Comment by Alcanderian** [comment]
尝试修复了一下export会使用GPU的问题，如果想使用没有GPU的机器导出模型可以更新代码试试
#26

**Comment by Alcanderian** [comment]
HF转换脚本BUG已在该pr中修复

#27

**Comment by zbtrs** [comment]
感谢
